-- Create sequences
create sequence f2a_job_s start with 1 increment by 1;

-- create tables
create table f2a_file_status_codes (
    security_group_id              number not null,
    code                           varchar2(20) not null
                                   constraint f2a_file_status_co_code_pk primary key,
    name                           varchar2(100) not null,
    css_class                      varchar2(100),
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;

create table f2a_projects (
    id                             number generated by default on null as identity  
                                   constraint f2a_projects_id_pk primary key,
    security_group_id              number not null,
    name                           varchar2(255) not null,
    description                    varchar2(2000),
    start_date                     date,
    deadline_date                  date,
    workspace_name                 varchar2(30),
    short_name                     varchar2(10),
    estimate_hr                    number,
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;

create table f2a_files (
    id                             number generated by default on null as identity  
                                   constraint f2a_files_id_pk primary key,
    project_id                     number
                                   constraint f2a_files_project_id_fk
                                   references f2a_projects on delete cascade,
    security_group_id              number not null,
    file_type                      varchar2(4000),
    file_name                      varchar2(500) not null,
    content_type                   varchar2(200),
    status_code                    varchar2(20) not null
                                   constraint f2a_files_status_code_fk
                                   references f2a_file_status_codes (code) on delete cascade,
    content                        clob,
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;

create table f2a_modules (
    id                             number generated by default on null as identity  
                                   constraint f2a_modules_id_pk primary key,
    project_id                     number
                                   constraint f2a_modules_project_id_fk
                                   references f2a_projects on delete cascade,
    file_id                        number constraint f2a_module_file_id_fk
                                   references f2a_files (id),
    security_group_id              number not null,
    module_type                    varchar2(20) not null,
    module_name                    varchar2(100) not null,
    content_type                   varchar2(30),
    content                        clob,
    title                          varchar2(60),
    version_no                     varchar2(20),
    query_based                    varchar2(4000),
    parent_id                      number
                                   constraint f2a_modules_parent_id_fk
                                   references f2a_modules on delete cascade,
    help_text                      varchar2(2000),
    item_label                     varchar2(200),
    item_length                    number,
    database_item                  varchar2(30),
    lov_module_id                  number
                                   constraint f2a_modules_lov_module_id_fk
                                   references f2a_modules (id) on delete cascade,
    data_type                      varchar2(100),
    required_flag                  varchar2(10) default on null 'false' not null,
    migrate_flag                   varchar2(1) default on null 'N' not null,
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;


-- triggers
create or replace trigger f2a_file_status_codes_biu
    before insert or update 
    on f2a_file_status_codes
    for each row
begin
    if :new.security_group_id is null then
        :new.security_group_id := 0;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end f2a_file_status_codes_biu;
/

create or replace trigger f2a_projects_biu
    before insert or update 
    on f2a_projects
    for each row
begin
    if :new.security_group_id is null then
        :new.security_group_id := 0;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end f2a_projects_biu;
/

create or replace trigger f2a_files_biu
    before insert or update 
    on f2a_files
    for each row
begin
    if :new.security_group_id is null then
        :new.security_group_id := 0;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end f2a_files_biu;
/

create or replace trigger f2a_modules_biu
    before insert or update 
    on f2a_modules
    for each row
begin
    if :new.security_group_id is null then
        :new.security_group_id := 0;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end f2a_modules_biu;
/


-- indexes
create index f2a_files_i1 on f2a_files (project_id);
create index f2a_files_i2 on f2a_files (status_code);
create index f2a_modules_i1 on f2a_modules (lov_module_id);
create index f2a_modules_i2 on f2a_modules (parent_id);
create index f2a_modules_i3 on f2a_modules (project_id);
create index f2a_modules_i4 on f2a_modules (file_id);

-- load data
 
Insert into F2A_FILE_STATUS_CODES (CODE,NAME,CSS_CLASS) values ('INSERTED','The file has been uploaded','fa fa-spinner fa-anim-spin');
Insert into F2A_FILE_STATUS_CODES (CODE,NAME,CSS_CLASS) values ('PROCESSED','The files has been processed successfully','fa fa-check-circle-o fam-100-percent fam-is-success');
COMMIT;

-- Generated by Quick SQL Sunday February 10, 2019  07:18:38
 
/*
file_status_codes
  code vc20 /pk
  name vc100 /nn
  css_class vc100
projects
   name /uk /nn
   description vc2000
   start_date d
   deadline_date d
   workspace_name vc30
   short_name vc10
   estimate_hr num
   files 
      file_type / nn vc20
      file_name /nn vc500
      content_type vc200
      status_code /references file_status_codes
      content clob
  modules
    module_type vc20 /nn
    module_name vc100 /nn
    content_type vc 30
    content clob
    title vc60
    version_no vc20
    query_based
    parent_id /references modules
    query_based
    help_text vc2000
    item_label vc200
    item_length num
    database_item vc30
    lov_module_id /references module
    migrate_flag vc1 /nn /default N /values Y,N

# settings = { prefix: "f2a", auditCols: true, SecurityGroupID: true, language: "EN", APEX: true }
*/
